# Generated by Django 5.1.4 on 2025-09-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='district',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='state',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
