# Generated by Django 5.1.4 on 2025-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donor_district_donor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='district',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='state',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
