# Generated by Django 5.1.4 on 2025-09-23 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hospital_verified_alter_hospital_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='password',
            field=models.CharField(default='temp123', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
