# Generated by Django 5.1.4 on 2025-09-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hospital_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='verified',
        ),
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
