# Generated by Django 5.1.4 on 2025-09-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_hospital_description_remove_hospital_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
