# Generated by Django 5.1.4 on 2025-09-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_donor_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_illness', models.BooleanField(default=False)),
                ('alcohol_24h', models.BooleanField(default=False)),
                ('tattoo_6m', models.BooleanField(default=False)),
                ('surgery_6m', models.BooleanField(default=False)),
                ('chronic_disease', models.BooleanField(default=False)),
                ('pregnant', models.BooleanField(default=False)),
                ('eligible', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donor')),
            ],
        ),
    ]
