# Generated by Django 5.1.4 on 2025-09-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_donorhealthcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorhealthcheck',
            name='age',
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorhealthcheck',
            name='covid_recent',
            field=models.BooleanField(default=False, help_text='COVID-19 positive in the last 28 days?'),
        ),
        migrations.AddField(
            model_name='donorhealthcheck',
            name='hemoglobin_level',
            field=models.FloatField(default=1, help_text='g/dL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorhealthcheck',
            name='medication',
            field=models.BooleanField(default=False, help_text='Currently taking any medications?'),
        ),
        migrations.AddField(
            model_name='donorhealthcheck',
            name='smoking',
            field=models.BooleanField(default=False, help_text='Smoked in the last 24 hours?'),
        ),
        migrations.AddField(
            model_name='donorhealthcheck',
            name='travel_malaria',
            field=models.BooleanField(default=False, help_text='Traveled to malaria-prone areas in the last 3 months?'),
        ),
        migrations.AddField(
            model_name='donorhealthcheck',
            name='weight',
            field=models.FloatField(default='18', help_text='Weight in kg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donorhealthcheck',
            name='alcohol_24h',
            field=models.BooleanField(default=False, help_text='Consumed alcohol in the last 24 hours?'),
        ),
        migrations.AlterField(
            model_name='donorhealthcheck',
            name='chronic_disease',
            field=models.BooleanField(default=False, help_text='Any chronic diseases (Diabetes, Heart, Cancer, etc.)?'),
        ),
        migrations.AlterField(
            model_name='donorhealthcheck',
            name='eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donorhealthcheck',
            name='pregnant',
            field=models.BooleanField(default=False, help_text='Currently pregnant?'),
        ),
        migrations.AlterField(
            model_name='donorhealthcheck',
            name='recent_illness',
            field=models.BooleanField(default=False, help_text='Any recent illness in the last 2 weeks?'),
        ),
        migrations.AlterField(
            model_name='donorhealthcheck',
            name='surgery_6m',
            field=models.BooleanField(default=False, help_text='Undergone surgery in the last 6 months?'),
        ),
        migrations.AlterField(
            model_name='donorhealthcheck',
            name='tattoo_6m',
            field=models.BooleanField(default=False, help_text='Had a tattoo/piercing in the last 6 months?'),
        ),
    ]
