# Generated by Django 5.1.4 on 2025-09-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_donorhealthcheck_age_donorhealthcheck_covid_recent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorhealthcheck',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.donor'),
        ),
    ]
