# Generated by Django 5.1.4 on 2025-10-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_donorhealthcheck_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
