# Generated by Django 5.1.4 on 2025-10-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bloodrequest_urgent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='urgent',
        ),
    ]
