# Generated by Django 5.1.4 on 2025-10-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_bloodrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
