# Generated by Django 5.1.4 on 2025-10-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bloodrequest_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='gender',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
