# Generated by Django 5.1.4 on 2025-10-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_bloodrequest_age_bloodrequest_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5)),
                ('units', models.PositiveIntegerField(default=1)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='core.hospital')),
            ],
        ),
    ]
