# Generated by Django 5.1.4 on 2025-10-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_donorrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorrequest',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='donorrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
