# Generated by Django 5.1.4 on 2025-10-05 06:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_donorrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
