# Generated by Django 5.1.4 on 2025-10-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_donorrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
