# Generated by Django 5.1.4 on 2025-10-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_donorrequest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='badge',
            field=models.CharField(choices=[('New Donor', 'New Donor'), ('Regular Donor', 'Regular Donor'), ('Life Saver', 'Life Saver'), ('Hero', 'Hero')], default='New Donor', max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='total_donations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
