# Generated by Django 5.1.4 on 2025-10-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
