# Generated by Django 5.1.4 on 2025-10-12 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_bloodstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodstock',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blood_stocks', to='core.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='units_available',
            field=models.IntegerField(),
        ),
    ]
