# Generated by Django 5.1.4 on 2025-10-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_bloodstock_hospital_alter_bloodstock_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodstock',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='units_available',
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='blood_type',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='units',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
